### ISSUE TITLE
Firefox bug

### ISSUE THREAD

**Issue by pinceladasdaweb** [lukakerr/lightweight-slider#1]
Congratulations on the great work, but on my test in Firefox, I ended up finding a bug. Look at how the slide behaves:

![Firefox Bug](https://i.imgur.com/DuX7mia.png)

I'm using FIrefox 55.0.3 on Mac OS.

**Comment by lukakerr** [comment]
Thanks for submitting an issue, this has been fixed in commit fc54636. Firefox doesn't like floats. The [demo](https://lukakerr.github.io/projects/lightweight-slider/demo.html) has also been updated
